begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crplnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_nonprd2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_natveg2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_others2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_crarea2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_grslnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2020" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2025" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2030" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2035" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2040" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2045" numeric;commit;
begin;alter table "output_bazil_luccme_biomes" add column if not exists "base_pltfor2050" numeric;commit;

begin;update "output_bazil_luccme_biomes" set "base_crplnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crplnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_nonprd2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_natveg2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_others2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_crarea2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_grslnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2020" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2025" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2030" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2035" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2040" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2045" = 0.0;commit;
begin;update "output_bazil_luccme_biomes" set "base_pltfor2050" = 0.0;commit;



