begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crplnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_nonprd2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_natveg2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_restor2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_others2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_crarea2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_grslnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2020" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2025" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2030" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2035" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2040" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2045" numeric;commit;
begin;alter table "output_bazil_luccme_states" add column if not exists "fcplusnz_pltfor2050" numeric;commit;

begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crplnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_nonprd2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_natveg2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_restor2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_others2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_crarea2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_grslnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2020" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2025" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2030" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2035" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2040" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2045" = 0.0;commit;
begin;update "output_bazil_luccme_states" set "fcplusnz_pltfor2050" = 0.0;commit;