begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crplnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_nonprd2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_natveg2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_restor2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_others2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_crarea2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_grslnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2020" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2025" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2030" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2035" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2040" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2045" numeric;commit;
begin;alter table "output_bazil_luccme_brazil" add column if not exists "fc_pltfor2050" numeric;commit;

begin;update "output_bazil_luccme_brazil" set "fc_crplnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2020" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2025" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2030" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2035" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2040" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2045" = 0.0;commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2050" = 0.0;commit;

begin;update "output_bazil_luccme_brazil" set "fc_crplnd2020" = (select trunc(sum( "crplnd2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2025" = (select trunc(sum( "crplnd2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2030" = (select trunc(sum( "crplnd2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2035" = (select trunc(sum( "crplnd2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2040" = (select trunc(sum( "crplnd2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2045" = (select trunc(sum( "crplnd2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crplnd2050" = (select trunc(sum( "crplnd2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2020" = (select trunc(sum( "nonprd2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2025" = (select trunc(sum( "nonprd2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2030" = (select trunc(sum( "nonprd2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2035" = (select trunc(sum( "nonprd2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2040" = (select trunc(sum( "nonprd2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2045" = (select trunc(sum( "nonprd2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_nonprd2050" = (select trunc(sum( "nonprd2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2020" = (select trunc(sum( "natveg2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2025" = (select trunc(sum( "natveg2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2030" = (select trunc(sum( "natveg2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2035" = (select trunc(sum( "natveg2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2040" = (select trunc(sum( "natveg2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2045" = (select trunc(sum( "natveg2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_natveg2050" = (select trunc(sum( "natveg2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2025" = (select trunc(sum( "restor2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2030" = (select trunc(sum( "restor2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2035" = (select trunc(sum( "restor2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2040" = (select trunc(sum( "restor2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2045" = (select trunc(sum( "restor2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_restor2050" = (select trunc(sum( "restor2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2020" = (select trunc(sum( "others2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2025" = (select trunc(sum( "others2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2030" = (select trunc(sum( "others2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2035" = (select trunc(sum( "others2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2040" = (select trunc(sum( "others2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2045" = (select trunc(sum( "others2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_others2050" = (select trunc(sum( "others2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2020" = (select trunc(sum( "crarea2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2025" = (select trunc(sum( "crarea2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2030" = (select trunc(sum( "crarea2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2035" = (select trunc(sum( "crarea2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2040" = (select trunc(sum( "crarea2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2045" = (select trunc(sum( "crarea2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_crarea2050" = (select trunc(sum( "crarea2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2020" = (select trunc(sum( "grslnd2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2025" = (select trunc(sum( "grslnd2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2030" = (select trunc(sum( "grslnd2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2035" = (select trunc(sum( "grslnd2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2040" = (select trunc(sum( "grslnd2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2045" = (select trunc(sum( "grslnd2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_grslnd2050" = (select trunc(sum( "grslnd2050" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2020" = (select trunc(sum( "pltfor2020" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2025" = (select trunc(sum( "pltfor2025" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2030" = (select trunc(sum( "pltfor2030" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2035" = (select trunc(sum( "pltfor2035" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2040" = (select trunc(sum( "pltfor2040" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2045" = (select trunc(sum( "pltfor2045" ), 3) from "bazil_luccme_cr_fc");commit;
begin;update "output_bazil_luccme_brazil" set "fc_pltfor2050" = (select trunc(sum( "pltfor2050" ), 3) from "bazil_luccme_cr_fc");commit;
