begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crplnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_nonprd2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_natveg2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_restor2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_others2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_crarea2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_grslnd2050" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2020" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2025" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2030" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2035" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2040" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2045" numeric;commit;
begin;alter table "output_bazil_luccme_regions" add column if not exists "fc_pltfor2050" numeric;commit;

begin;update "output_bazil_luccme_regions" set "fc_crplnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crplnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_nonprd2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_natveg2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_restor2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_others2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_crarea2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_grslnd2050" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2020" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2025" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2030" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2035" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2040" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2045" = 0.0;commit;
begin;update "output_bazil_luccme_regions" set "fc_pltfor2050" = 0.0;commit;